# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Setup keyfile
  boot.initrd.secrets = {
    "/crypto_keyfile.bin" = null;
  };

  # Enable swap on luks
  boot.initrd.luks.devices."luks-b0f6eaaf-cbf3-4cb0-b3ce-fa74a7352c43".device = "/dev/disk/by-uuid/b0f6eaaf-cbf3-4cb0-b3ce-fa74a7352c43";
  boot.initrd.luks.devices."luks-b0f6eaaf-cbf3-4cb0-b3ce-fa74a7352c43".keyFile = "/crypto_keyfile.bin";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1c83d559-82a7-4307-bbc6-928dc290558a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-182dcbab-331e-401d-bd87-4d34ce023bc2".device = "/dev/disk/by-uuid/182dcbab-331e-401d-bd87-4d34ce023bc2";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/63AC-C95C";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b6ac3c86-8664-46b7-b0c8-5f128f536fc8"; }
    ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
